### ISSUE TITLE
withStore(null, ['foo']) not working

### ISSUE THREAD

**Issue by janis-kra** [objectliteral/fleux#8]
Calling `withStore(null, ['foo'])` gives the following error:

```
TypeError: withStore.apply(...) is not a function

This error is located at:
    in Unknown (at hoc.js:79)
    in Unknown (at hoc.js:110)
...
```

`withStore([], ['foo'])` works fine, so editing the docs to reflect this would suffice

**Comment by objectliteral** [comment]
It seems, I was a bit overeager when updating the README. A fix has been pushed.

Note, however, that `withStore` does not yet use the same argument checking. I want to refactor that a bit, but add tests specific to `withStore` before touching the code.
